config/routes.rb
Shop::Application.routes.draw do
  devise_for :users
  resources :products
  root 'products#index'
  resources :prices

  resources :categories

  

  namespace :admin do
    resources :products
    root 'products#index'

    resources :categories
    resources :prices
  end
end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :product
end

app/controllers/admin/prices_controller.rb
class Admin::PricesController < Admin::AdminController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)

    respond_to do |format|
      if @price.save
        format.html { redirect_to admin_price_path(@price), notice: 'Price was successfully created.' }
        format.json { render action: 'show', status: :created, location: @price }
      else
        format.html { render action: 'new' }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to admin_price_path(@price), notice: 'Price was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to admin_prices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:value)
    end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show]

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new

  # GET /prices/1/edit

  # POST /prices
  # POST /prices.json

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json

  # DELETE /prices/1
  # DELETE /prices/1.json

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:value)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/admin/prices/_form.html.erb
<%= form_for(@price,:url=>admin_price_path(@price)) do |f| %>
  <% if @price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% @price.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/prices/edit.html.erb
<h1>Editing price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', admin_prices_path %>

app/views/admin/prices/index.html.erb
<h1>Listing prices</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.value %></td>
        <td><%= link_to 'Show', admin_price_path(price) %></td>
        <td><%= link_to 'Edit', edit_admin_price_path(price) %></td>
        <td><%= link_to 'Destroy', admin_price_path(price), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_admin_price_path %>

app/views/admin/prices/new.html.erb
<h1>New price</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_prices_path %>

app/views/admin/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @price.value %>
</p>

<%= link_to 'Edit', edit_admin_price_path(@price) %> |
<%= link_to 'Back', admin_prices_path %>